<?php

namespace Modules\Backend\System\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CountryMasterData extends Seeder
{
    public $priority = 5;

    public function run()
    {
        $seedName = static::class;
        $exists = $this->db->table('seedHistory')->where('seedName', $seedName)->countAllResults();
        if ($exists > 0) {
            return;
        }

        $countryData = [
            ['countryName' => 'Afghanistan', 'iso3Code' => 'AFG', 'iso2Code' => 'AF', 'phoneCode' => '93', 'currencyCode' => 'AFN', 'currencyName' => 'Afghan afghani',    'currencySymbol' => '؋', 'flagEmoji' => '🇦🇫'],
            ['countryName' => 'Aland Islands', 'iso3Code' => 'ALA', 'iso2Code' => 'AX', 'phoneCode' => '+358-18', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇦🇽'],
            ['countryName' => 'Albania', 'iso3Code' => 'ALB', 'iso2Code' => 'AL', 'phoneCode' => '355', 'currencyCode' => 'ALL', 'currencyName' => 'Albanian lek',    'currencySymbol' => 'Lek', 'flagEmoji' => '🇦🇱'],
            ['countryName' => 'Algeria', 'iso3Code' => 'DZA', 'iso2Code' => 'DZ', 'phoneCode' => '213', 'currencyCode' => 'DZD', 'currencyName' => 'Algerian dinar',    'currencySymbol' => 'دج', 'flagEmoji' => '🇩🇿'],
            ['countryName' => 'American Samoa', 'iso3Code' => 'ASM', 'iso2Code' => 'AS', 'phoneCode' => '+1-684', 'currencyCode' => 'USD', 'currencyName' => 'US Dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇸'],
            ['countryName' => 'Andorra', 'iso3Code' => 'AND', 'iso2Code' => 'AD', 'phoneCode' => '376', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇦🇩'],
            ['countryName' => 'Angola', 'iso3Code' => 'AGO', 'iso2Code' => 'AO', 'phoneCode' => '244', 'currencyCode' => 'AOA', 'currencyName' => 'Angolan kwanza',    'currencySymbol' => 'Kz', 'flagEmoji' => '🇦🇴'],
            ['countryName' => 'Anguilla', 'iso3Code' => 'AIA', 'iso2Code' => 'AI', 'phoneCode' => '+1-264', 'currencyCode' => 'XCD', 'currencyName' => 'East Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇮'],
            ['countryName' => 'Antarctica', 'iso3Code' => 'ATA', 'iso2Code' => 'AQ', 'phoneCode' => '672', 'currencyCode' => 'AAD', 'currencyName' => 'Antarctican dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇶'],
            ['countryName' => 'Antigua And Barbuda', 'iso3Code' => 'ATG', 'iso2Code' => 'AG', 'phoneCode' => '+1-268', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇬'],
            ['countryName' => 'Argentina', 'iso3Code' => 'ARG', 'iso2Code' => 'AR', 'phoneCode' => '54', 'currencyCode' => 'ARS', 'currencyName' => 'Argentine peso',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇷'],
            ['countryName' => 'Armenia', 'iso3Code' => 'ARM', 'iso2Code' => 'AM', 'phoneCode' => '374', 'currencyCode' => 'AMD', 'currencyName' => 'Armenian dram',    'currencySymbol' => '֏', 'flagEmoji' => '🇦🇲'],
            ['countryName' => 'Aruba', 'iso3Code' => 'ABW', 'iso2Code' => 'AW', 'phoneCode' => '297', 'currencyCode' => 'AWG', 'currencyName' => 'Aruban florin',    'currencySymbol' => 'ƒ', 'flagEmoji' => '🇦🇼'],
            ['countryName' => 'Australia', 'iso3Code' => 'AUS', 'iso2Code' => 'AU', 'phoneCode' => '61', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇦🇺'],
            ['countryName' => 'Austria', 'iso3Code' => 'AUT', 'iso2Code' => 'AT', 'phoneCode' => '43', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇦🇹'],
            ['countryName' => 'Azerbaijan', 'iso3Code' => 'AZE', 'iso2Code' => 'AZ', 'phoneCode' => '994', 'currencyCode' => 'AZN', 'currencyName' => 'Azerbaijani manat',    'currencySymbol' => 'm', 'flagEmoji' => '🇦🇿'],
            ['countryName' => 'The Bahamas', 'iso3Code' => 'BHS', 'iso2Code' => 'BS', 'phoneCode' => '+1-242', 'currencyCode' => 'BSD', 'currencyName' => 'Bahamian dollar',    'currencySymbol' => 'B$', 'flagEmoji' => '🇧🇸'],
            ['countryName' => 'Bahrain', 'iso3Code' => 'BHR', 'iso2Code' => 'BH', 'phoneCode' => '973', 'currencyCode' => 'BHD', 'currencyName' => 'Bahraini dinar',    'currencySymbol' => '.د.ب', 'flagEmoji' => '🇧🇭'],
            ['countryName' => 'Bangladesh', 'iso3Code' => 'BGD', 'iso2Code' => 'BD', 'phoneCode' => '880', 'currencyCode' => 'BDT', 'currencyName' => 'Bangladeshi taka',    'currencySymbol' => '৳', 'flagEmoji' => '🇧🇩'],
            ['countryName' => 'Barbados', 'iso3Code' => 'BRB', 'iso2Code' => 'BB', 'phoneCode' => '+1-246', 'currencyCode' => 'BBD', 'currencyName' => 'Barbadian dollar',    'currencySymbol' => 'Bds$', 'flagEmoji' => '🇧🇧'],
            ['countryName' => 'Belarus', 'iso3Code' => 'BLR', 'iso2Code' => 'BY', 'phoneCode' => '375', 'currencyCode' => 'BYN', 'currencyName' => 'Belarusian ruble',    'currencySymbol' => 'Br', 'flagEmoji' => '🇧🇾'],
            ['countryName' => 'Belgium', 'iso3Code' => 'BEL', 'iso2Code' => 'BE', 'phoneCode' => '32', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇧🇪'],
            ['countryName' => 'Belize', 'iso3Code' => 'BLZ', 'iso2Code' => 'BZ', 'phoneCode' => '501', 'currencyCode' => 'BZD', 'currencyName' => 'Belize dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇧🇿'],
            ['countryName' => 'Benin', 'iso3Code' => 'BEN', 'iso2Code' => 'BJ', 'phoneCode' => '229', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇧🇯'],
            ['countryName' => 'Bermuda', 'iso3Code' => 'BMU', 'iso2Code' => 'BM', 'phoneCode' => '+1-441', 'currencyCode' => 'BMD', 'currencyName' => 'Bermudian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇧🇲'],
            ['countryName' => 'Bhutan', 'iso3Code' => 'BTN', 'iso2Code' => 'BT', 'phoneCode' => '975', 'currencyCode' => 'BTN', 'currencyName' => 'Bhutanese ngultrum',    'currencySymbol' => 'Nu.', 'flagEmoji' => '🇧🇹'],
            ['countryName' => 'Bolivia', 'iso3Code' => 'BOL', 'iso2Code' => 'BO', 'phoneCode' => '591', 'currencyCode' => 'BOB', 'currencyName' => 'Bolivian boliviano',    'currencySymbol' => 'Bs.', 'flagEmoji' => '🇧🇴'],
            ['countryName' => 'Bosnia and Herzegovina', 'iso3Code' => 'BIH', 'iso2Code' => 'BA', 'phoneCode' => '387', 'currencyCode' => 'BAM', 'currencyName' => 'Bosnia and Herzegovina convertible mark',    'currencySymbol' => 'KM', 'flagEmoji' => '🇧🇦'],
            ['countryName' => 'Botswana', 'iso3Code' => 'BWA', 'iso2Code' => 'BW', 'phoneCode' => '267', 'currencyCode' => 'BWP', 'currencyName' => 'Botswana pula',    'currencySymbol' => 'P', 'flagEmoji' => '🇧🇼'],
            ['countryName' => 'Bouvet Island', 'iso3Code' => 'BVT', 'iso2Code' => 'BV', 'phoneCode' => '55', 'currencyCode' => 'NOK', 'currencyName' => 'Norwegian Krone',    'currencySymbol' => 'kr', 'flagEmoji' => '🇧🇻'],
            ['countryName' => 'Brazil', 'iso3Code' => 'BRA', 'iso2Code' => 'BR', 'phoneCode' => '55', 'currencyCode' => 'BRL', 'currencyName' => 'Brazilian real',    'currencySymbol' => 'R$', 'flagEmoji' => '🇧🇷'],
            ['countryName' => 'British Indian Ocean Territory', 'iso3Code' => 'IOT', 'iso2Code' => 'IO', 'phoneCode' => '246', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇮🇴'],
            ['countryName' => 'Brunei', 'iso3Code' => 'BRN', 'iso2Code' => 'BN', 'phoneCode' => '673', 'currencyCode' => 'BND', 'currencyName' => 'Brunei dollar',    'currencySymbol' => 'B$', 'flagEmoji' => '🇧🇳'],
            ['countryName' => 'Bulgaria', 'iso3Code' => 'BGR', 'iso2Code' => 'BG', 'phoneCode' => '359', 'currencyCode' => 'BGN', 'currencyName' => 'Bulgarian lev',    'currencySymbol' => 'Лв.', 'flagEmoji' => '🇧🇬'],
            ['countryName' => 'Burkina Faso', 'iso3Code' => 'BFA', 'iso2Code' => 'BF', 'phoneCode' => '226', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇧🇫'],
            ['countryName' => 'Burundi', 'iso3Code' => 'BDI', 'iso2Code' => 'BI', 'phoneCode' => '257', 'currencyCode' => 'BIF', 'currencyName' => 'Burundian franc',    'currencySymbol' => 'FBu', 'flagEmoji' => '🇧🇮'],
            ['countryName' => 'Cambodia', 'iso3Code' => 'KHM', 'iso2Code' => 'KH', 'phoneCode' => '855', 'currencyCode' => 'KHR', 'currencyName' => 'Cambodian riel',    'currencySymbol' => 'KHR', 'flagEmoji' => '🇰🇭'],
            ['countryName' => 'Cameroon', 'iso3Code' => 'CMR', 'iso2Code' => 'CM', 'phoneCode' => '237', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FCFA', 'flagEmoji' => '🇨🇲'],
            ['countryName' => 'Canada', 'iso3Code' => 'CAN', 'iso2Code' => 'CA', 'phoneCode' => '1', 'currencyCode' => 'CAD', 'currencyName' => 'Canadian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇦'],
            ['countryName' => 'Cape Verde', 'iso3Code' => 'CPV', 'iso2Code' => 'CV', 'phoneCode' => '238', 'currencyCode' => 'CVE', 'currencyName' => 'Cape Verdean escudo',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇻'],
            ['countryName' => 'Cayman Islands', 'iso3Code' => 'CYM', 'iso2Code' => 'KY', 'phoneCode' => '+1-345', 'currencyCode' => 'KYD', 'currencyName' => 'Cayman Islands dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇰🇾'],
            ['countryName' => 'Central African Republic', 'iso3Code' => 'CAF', 'iso2Code' => 'CF', 'phoneCode' => '236', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FCFA', 'flagEmoji' => '🇨🇫'],
            ['countryName' => 'Chad', 'iso3Code' => 'TCD', 'iso2Code' => 'TD', 'phoneCode' => '235', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FCFA', 'flagEmoji' => '🇹🇩'],
            ['countryName' => 'Chile', 'iso3Code' => 'CHL', 'iso2Code' => 'CL', 'phoneCode' => '56', 'currencyCode' => 'CLP', 'currencyName' => 'Chilean peso',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇱'],
            ['countryName' => 'China', 'iso3Code' => 'CHN', 'iso2Code' => 'CN', 'phoneCode' => '86', 'currencyCode' => 'CNY', 'currencyName' => 'Chinese yuan',    'currencySymbol' => '¥', 'flagEmoji' => '🇨🇳'],
            ['countryName' => 'Christmas Island', 'iso3Code' => 'CXR', 'iso2Code' => 'CX', 'phoneCode' => '61', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇽'],
            ['countryName' => 'Cocos (Keeling) Islands', 'iso3Code' => 'CCK', 'iso2Code' => 'CC', 'phoneCode' => '61', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇨'],
            ['countryName' => 'Colombia', 'iso3Code' => 'COL', 'iso2Code' => 'CO', 'phoneCode' => '57', 'currencyCode' => 'COP', 'currencyName' => 'Colombian peso',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇴'],
            ['countryName' => 'Comoros', 'iso3Code' => 'COM', 'iso2Code' => 'KM', 'phoneCode' => '269', 'currencyCode' => 'KMF', 'currencyName' => 'Comorian franc',    'currencySymbol' => 'CF', 'flagEmoji' => '🇰🇲'],
            ['countryName' => 'Congo', 'iso3Code' => 'COG', 'iso2Code' => 'CG', 'phoneCode' => '242', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FC', 'flagEmoji' => '🇨🇬'],
            ['countryName' => 'Democratic Republic of the Congo', 'iso3Code' => 'COD', 'iso2Code' => 'CD', 'phoneCode' => '243', 'currencyCode' => 'CDF', 'currencyName' => 'Congolese Franc',    'currencySymbol' => 'FC', 'flagEmoji' => '🇨🇩'],
            ['countryName' => 'Cook Islands', 'iso3Code' => 'COK', 'iso2Code' => 'CK', 'phoneCode' => '682', 'currencyCode' => 'NZD', 'currencyName' => 'Cook Islands dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇰'],
            ['countryName' => 'Costa Rica', 'iso3Code' => 'CRI', 'iso2Code' => 'CR', 'phoneCode' => '506', 'currencyCode' => 'CRC', 'currencyName' => 'Costa Rican colón',    'currencySymbol' => '₡', 'flagEmoji' => '🇨🇷'],
            ['countryName' => 'Cote D\'Ivoire (Ivory Coast)', 'iso3Code' => 'CIV', 'iso2Code' => 'CI', 'phoneCode' => '225', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇨🇮'],
            ['countryName' => 'Croatia', 'iso3Code' => 'HRV', 'iso2Code' => 'HR', 'phoneCode' => '385', 'currencyCode' => 'HRK', 'currencyName' => 'Croatian kuna',    'currencySymbol' => 'kn', 'flagEmoji' => '🇭🇷'],
            ['countryName' => 'Cuba', 'iso3Code' => 'CUB', 'iso2Code' => 'CU', 'phoneCode' => '53', 'currencyCode' => 'CUP', 'currencyName' => 'Cuban peso',    'currencySymbol' => '$', 'flagEmoji' => '🇨🇺'],
            ['countryName' => 'Cyprus', 'iso3Code' => 'CYP', 'iso2Code' => 'CY', 'phoneCode' => '357', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇨🇾'],
            ['countryName' => 'Czech Republic', 'iso3Code' => 'CZE', 'iso2Code' => 'CZ', 'phoneCode' => '420', 'currencyCode' => 'CZK', 'currencyName' => 'Czech koruna',    'currencySymbol' => 'Kč', 'flagEmoji' => '🇨🇿'],
            ['countryName' => 'Denmark', 'iso3Code' => 'DNK', 'iso2Code' => 'DK', 'phoneCode' => '45', 'currencyCode' => 'DKK', 'currencyName' => 'Danish krone',    'currencySymbol' => 'Kr.', 'flagEmoji' => '🇩🇰'],
            ['countryName' => 'Djibouti', 'iso3Code' => 'DJI', 'iso2Code' => 'DJ', 'phoneCode' => '253', 'currencyCode' => 'DJF', 'currencyName' => 'Djiboutian franc',    'currencySymbol' => 'Fdj', 'flagEmoji' => '🇩🇯'],
            ['countryName' => 'Dominica', 'iso3Code' => 'DMA', 'iso2Code' => 'DM', 'phoneCode' => '+1-767', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇩🇲'],
            ['countryName' => 'Dominican Republic', 'iso3Code' => 'DOM', 'iso2Code' => 'DO', 'phoneCode' => '+1-809 and 1-829', 'currencyCode' => 'DOP', 'currencyName' => 'Dominican peso',    'currencySymbol' => '$', 'flagEmoji' => '🇩🇴'],
            ['countryName' => 'East Timor', 'iso3Code' => 'TLS', 'iso2Code' => 'TL', 'phoneCode' => '670', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇱'],
            ['countryName' => 'Ecuador', 'iso3Code' => 'ECU', 'iso2Code' => 'EC', 'phoneCode' => '593', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇪🇨'],
            ['countryName' => 'Egypt', 'iso3Code' => 'EGY', 'iso2Code' => 'EG', 'phoneCode' => '20', 'currencyCode' => 'EGP', 'currencyName' => 'Egyptian pound',    'currencySymbol' => 'ج.م', 'flagEmoji' => '🇪🇬'],
            ['countryName' => 'El Salvador', 'iso3Code' => 'SLV', 'iso2Code' => 'SV', 'phoneCode' => '503', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇸🇻'],
            ['countryName' => 'Equatorial Guinea', 'iso3Code' => 'GNQ', 'iso2Code' => 'GQ', 'phoneCode' => '240', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FCFA', 'flagEmoji' => '🇬🇶'],
            ['countryName' => 'Eritrea', 'iso3Code' => 'ERI', 'iso2Code' => 'ER', 'phoneCode' => '291', 'currencyCode' => 'ERN', 'currencyName' => 'Eritrean nakfa',    'currencySymbol' => 'Nfk', 'flagEmoji' => '🇪🇷'],
            ['countryName' => 'Estonia', 'iso3Code' => 'EST', 'iso2Code' => 'EE', 'phoneCode' => '372', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇪🇪'],
            ['countryName' => 'Ethiopia', 'iso3Code' => 'ETH', 'iso2Code' => 'ET', 'phoneCode' => '251', 'currencyCode' => 'ETB', 'currencyName' => 'Ethiopian birr',    'currencySymbol' => 'Nkf', 'flagEmoji' => '🇪🇹'],
            ['countryName' => 'Falkland Islands', 'iso3Code' => 'FLK', 'iso2Code' => 'FK', 'phoneCode' => '500', 'currencyCode' => 'FKP', 'currencyName' => 'Falkland Islands pound',    'currencySymbol' => '£', 'flagEmoji' => '🇫🇰'],
            ['countryName' => 'Faroe Islands', 'iso3Code' => 'FRO', 'iso2Code' => 'FO', 'phoneCode' => '298', 'currencyCode' => 'DKK', 'currencyName' => 'Danish krone',    'currencySymbol' => 'Kr.', 'flagEmoji' => '🇫🇴'],
            ['countryName' => 'Fiji Islands', 'iso3Code' => 'FJI', 'iso2Code' => 'FJ', 'phoneCode' => '679', 'currencyCode' => 'FJD', 'currencyName' => 'Fijian dollar',    'currencySymbol' => 'FJ$', 'flagEmoji' => '🇫🇯'],
            ['countryName' => 'Finland', 'iso3Code' => 'FIN', 'iso2Code' => 'FI', 'phoneCode' => '358', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇫🇮'],
            ['countryName' => 'France', 'iso3Code' => 'FRA', 'iso2Code' => 'FR', 'phoneCode' => '33', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇫🇷'],
            ['countryName' => 'French Guiana', 'iso3Code' => 'GUF', 'iso2Code' => 'GF', 'phoneCode' => '594', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇬🇫'],
            ['countryName' => 'French Polynesia', 'iso3Code' => 'PYF', 'iso2Code' => 'PF', 'phoneCode' => '689', 'currencyCode' => 'XPF', 'currencyName' => 'CFP franc',    'currencySymbol' => '₣', 'flagEmoji' => '🇵🇫'],
            ['countryName' => 'French Southern Territories', 'iso3Code' => 'ATF', 'iso2Code' => 'TF', 'phoneCode' => '262', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇹🇫'],
            ['countryName' => 'Gabon', 'iso3Code' => 'GAB', 'iso2Code' => 'GA', 'phoneCode' => '241', 'currencyCode' => 'XAF', 'currencyName' => 'Central African CFA franc',    'currencySymbol' => 'FCFA', 'flagEmoji' => '🇬🇦'],
            ['countryName' => 'Gambia The', 'iso3Code' => 'GMB', 'iso2Code' => 'GM', 'phoneCode' => '220', 'currencyCode' => 'GMD', 'currencyName' => 'Gambian dalasi',    'currencySymbol' => 'D', 'flagEmoji' => '🇬🇲'],
            ['countryName' => 'Georgia', 'iso3Code' => 'GEO', 'iso2Code' => 'GE', 'phoneCode' => '995', 'currencyCode' => 'GEL', 'currencyName' => 'Georgian lari',    'currencySymbol' => 'ლ', 'flagEmoji' => '🇬🇪'],
            ['countryName' => 'Germany', 'iso3Code' => 'DEU', 'iso2Code' => 'DE', 'phoneCode' => '49', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇩🇪'],
            ['countryName' => 'Ghana', 'iso3Code' => 'GHA', 'iso2Code' => 'GH', 'phoneCode' => '233', 'currencyCode' => 'GHS', 'currencyName' => 'Ghanaian cedi',    'currencySymbol' => 'GH₵', 'flagEmoji' => '🇬🇭'],
            ['countryName' => 'Gibraltar', 'iso3Code' => 'GIB', 'iso2Code' => 'GI', 'phoneCode' => '350', 'currencyCode' => 'GIP', 'currencyName' => 'Gibraltar pound',    'currencySymbol' => '£', 'flagEmoji' => '🇬🇮'],
            ['countryName' => 'Greece', 'iso3Code' => 'GRC', 'iso2Code' => 'GR', 'phoneCode' => '30', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇬🇷'],
            ['countryName' => 'Greenland', 'iso3Code' => 'GRL', 'iso2Code' => 'GL', 'phoneCode' => '299', 'currencyCode' => 'DKK', 'currencyName' => 'Danish krone',    'currencySymbol' => 'Kr.', 'flagEmoji' => '🇬🇱'],
            ['countryName' => 'Grenada', 'iso3Code' => 'GRD', 'iso2Code' => 'GD', 'phoneCode' => '+1-473', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇬🇩'],
            ['countryName' => 'Guadeloupe', 'iso3Code' => 'GLP', 'iso2Code' => 'GP', 'phoneCode' => '590', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇬🇵'],
            ['countryName' => 'Guam', 'iso3Code' => 'GUM', 'iso2Code' => 'GU', 'phoneCode' => '+1-671', 'currencyCode' => 'USD', 'currencyName' => 'US Dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇬🇺'],
            ['countryName' => 'Guatemala', 'iso3Code' => 'GTM', 'iso2Code' => 'GT', 'phoneCode' => '502', 'currencyCode' => 'GTQ', 'currencyName' => 'Guatemalan quetzal',    'currencySymbol' => 'Q', 'flagEmoji' => '🇬🇹'],
            ['countryName' => 'Guernsey and Alderney', 'iso3Code' => 'GGY', 'iso2Code' => 'GG', 'phoneCode' => '+44-1481', 'currencyCode' => 'GBP', 'currencyName' => 'British pound',    'currencySymbol' => '£', 'flagEmoji' => '🇬🇬'],
            ['countryName' => 'Guinea', 'iso3Code' => 'GIN', 'iso2Code' => 'GN', 'phoneCode' => '224', 'currencyCode' => 'GNF', 'currencyName' => 'Guinean franc',    'currencySymbol' => 'FG', 'flagEmoji' => '🇬🇳'],
            ['countryName' => 'Guinea-Bissau', 'iso3Code' => 'GNB', 'iso2Code' => 'GW', 'phoneCode' => '245', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇬🇼'],
            ['countryName' => 'Guyana', 'iso3Code' => 'GUY', 'iso2Code' => 'GY', 'phoneCode' => '592', 'currencyCode' => 'GYD', 'currencyName' => 'Guyanese dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇬🇾'],
            ['countryName' => 'Haiti', 'iso3Code' => 'HTI', 'iso2Code' => 'HT', 'phoneCode' => '509', 'currencyCode' => 'HTG', 'currencyName' => 'Haitian gourde',    'currencySymbol' => 'G', 'flagEmoji' => '🇭🇹'],
            ['countryName' => 'Heard Island and McDonald Islands', 'iso3Code' => 'HMD', 'iso2Code' => 'HM', 'phoneCode' => '672', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇭🇲'],
            ['countryName' => 'Honduras', 'iso3Code' => 'HND', 'iso2Code' => 'HN', 'phoneCode' => '504', 'currencyCode' => 'HNL', 'currencyName' => 'Honduran lempira',    'currencySymbol' => 'L', 'flagEmoji' => '🇭🇳'],
            ['countryName' => 'Hong Kong S.A.R.', 'iso3Code' => 'HKG', 'iso2Code' => 'HK', 'phoneCode' => '852', 'currencyCode' => 'HKD', 'currencyName' => 'Hong Kong dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇭🇰'],
            ['countryName' => 'Hungary', 'iso3Code' => 'HUN', 'iso2Code' => 'HU', 'phoneCode' => '36', 'currencyCode' => 'HUF', 'currencyName' => 'Hungarian forint',    'currencySymbol' => 'Ft', 'flagEmoji' => '🇭🇺'],
            ['countryName' => 'Iceland', 'iso3Code' => 'ISL', 'iso2Code' => 'IS', 'phoneCode' => '354', 'currencyCode' => 'ISK', 'currencyName' => 'Icelandic króna',    'currencySymbol' => 'kr', 'flagEmoji' => '🇮🇸'],
            ['countryName' => 'India', 'iso3Code' => 'IND', 'iso2Code' => 'IN', 'phoneCode' => '91', 'currencyCode' => 'INR', 'currencyName' => 'Indian rupee',    'currencySymbol' => '₹', 'flagEmoji' => '🇮🇳'],
            ['countryName' => 'Indonesia', 'iso3Code' => 'IDN', 'iso2Code' => 'ID', 'phoneCode' => '62', 'currencyCode' => 'IDR', 'currencyName' => 'Indonesian rupiah',    'currencySymbol' => 'Rp', 'flagEmoji' => '🇮🇩'],
            ['countryName' => 'Iran', 'iso3Code' => 'IRN', 'iso2Code' => 'IR', 'phoneCode' => '98', 'currencyCode' => 'IRR', 'currencyName' => 'Iranian rial',    'currencySymbol' => '﷼', 'flagEmoji' => '🇮🇷'],
            ['countryName' => 'Iraq', 'iso3Code' => 'IRQ', 'iso2Code' => 'IQ', 'phoneCode' => '964', 'currencyCode' => 'IQD', 'currencyName' => 'Iraqi dinar',    'currencySymbol' => 'د.ع', 'flagEmoji' => '🇮🇶'],
            ['countryName' => 'Ireland', 'iso3Code' => 'IRL', 'iso2Code' => 'IE', 'phoneCode' => '353', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇮🇪'],
            ['countryName' => 'Israel', 'iso3Code' => 'ISR', 'iso2Code' => 'IL', 'phoneCode' => '972', 'currencyCode' => 'ILS', 'currencyName' => 'Israeli new shekel',    'currencySymbol' => '₪', 'flagEmoji' => '🇮🇱'],
            ['countryName' => 'Italy', 'iso3Code' => 'ITA', 'iso2Code' => 'IT', 'phoneCode' => '39', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇮🇹'],
            ['countryName' => 'Jamaica', 'iso3Code' => 'JAM', 'iso2Code' => 'JM', 'phoneCode' => '+1-876', 'currencyCode' => 'JMD', 'currencyName' => 'Jamaican dollar',    'currencySymbol' => 'J$', 'flagEmoji' => '🇯🇲'],
            ['countryName' => 'Japan', 'iso3Code' => 'JPN', 'iso2Code' => 'JP', 'phoneCode' => '81', 'currencyCode' => 'JPY', 'currencyName' => 'Japanese yen',    'currencySymbol' => '¥', 'flagEmoji' => '🇯🇵'],
            ['countryName' => 'Jersey', 'iso3Code' => 'JEY', 'iso2Code' => 'JE', 'phoneCode' => '+44-1534', 'currencyCode' => 'GBP', 'currencyName' => 'British pound',    'currencySymbol' => '£', 'flagEmoji' => '🇯🇪'],
            ['countryName' => 'Jordan', 'iso3Code' => 'JOR', 'iso2Code' => 'JO', 'phoneCode' => '962', 'currencyCode' => 'JOD', 'currencyName' => 'Jordanian dinar',    'currencySymbol' => 'ا.د', 'flagEmoji' => '🇯🇴'],
            ['countryName' => 'Kazakhstan', 'iso3Code' => 'KAZ', 'iso2Code' => 'KZ', 'phoneCode' => '7', 'currencyCode' => 'KZT', 'currencyName' => 'Kazakhstani tenge',    'currencySymbol' => 'лв', 'flagEmoji' => '🇰🇿'],
            ['countryName' => 'Kenya', 'iso3Code' => 'KEN', 'iso2Code' => 'KE', 'phoneCode' => '254', 'currencyCode' => 'KES', 'currencyName' => 'Kenyan shilling',    'currencySymbol' => 'KSh', 'flagEmoji' => '🇰🇪'],
            ['countryName' => 'Kiribati', 'iso3Code' => 'KIR', 'iso2Code' => 'KI', 'phoneCode' => '686', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇰🇮'],
            ['countryName' => 'North Korea', 'iso3Code' => 'PRK', 'iso2Code' => 'KP', 'phoneCode' => '850', 'currencyCode' => 'KPW', 'currencyName' => 'North Korean Won',    'currencySymbol' => '₩', 'flagEmoji' => '🇰🇵'],
            ['countryName' => 'South Korea', 'iso3Code' => 'KOR', 'iso2Code' => 'KR', 'phoneCode' => '82', 'currencyCode' => 'KRW', 'currencyName' => 'Won',    'currencySymbol' => '₩', 'flagEmoji' => '🇰🇷'],
            ['countryName' => 'Kuwait', 'iso3Code' => 'KWT', 'iso2Code' => 'KW', 'phoneCode' => '965', 'currencyCode' => 'KWD', 'currencyName' => 'Kuwaiti dinar',    'currencySymbol' => 'ك.د', 'flagEmoji' => '🇰🇼'],
            ['countryName' => 'Kyrgyzstan', 'iso3Code' => 'KGZ', 'iso2Code' => 'KG', 'phoneCode' => '996', 'currencyCode' => 'KGS', 'currencyName' => 'Kyrgyzstani som',    'currencySymbol' => 'лв', 'flagEmoji' => '🇰🇬'],
            ['countryName' => 'Laos', 'iso3Code' => 'LAO', 'iso2Code' => 'LA', 'phoneCode' => '856', 'currencyCode' => 'LAK', 'currencyName' => 'Lao kip',    'currencySymbol' => '₭', 'flagEmoji' => '🇱🇦'],
            ['countryName' => 'Latvia', 'iso3Code' => 'LVA', 'iso2Code' => 'LV', 'phoneCode' => '371', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇱🇻'],
            ['countryName' => 'Lebanon', 'iso3Code' => 'LBN', 'iso2Code' => 'LB', 'phoneCode' => '961', 'currencyCode' => 'LBP', 'currencyName' => 'Lebanese pound',    'currencySymbol' => '£', 'flagEmoji' => '🇱🇧'],
            ['countryName' => 'Lesotho', 'iso3Code' => 'LSO', 'iso2Code' => 'LS', 'phoneCode' => '266', 'currencyCode' => 'LSL', 'currencyName' => 'Lesotho loti',    'currencySymbol' => 'L', 'flagEmoji' => '🇱🇸'],
            ['countryName' => 'Liberia', 'iso3Code' => 'LBR', 'iso2Code' => 'LR', 'phoneCode' => '231', 'currencyCode' => 'LRD', 'currencyName' => 'Liberian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇱🇷'],
            ['countryName' => 'Libya', 'iso3Code' => 'LBY', 'iso2Code' => 'LY', 'phoneCode' => '218', 'currencyCode' => 'LYD', 'currencyName' => 'Libyan dinar',    'currencySymbol' => 'د.ل', 'flagEmoji' => '🇱🇾'],
            ['countryName' => 'Liechtenstein', 'iso3Code' => 'LIE', 'iso2Code' => 'LI', 'phoneCode' => '423', 'currencyCode' => 'CHF', 'currencyName' => 'Swiss franc',    'currencySymbol' => 'CHf', 'flagEmoji' => '🇱🇮'],
            ['countryName' => 'Lithuania', 'iso3Code' => 'LTU', 'iso2Code' => 'LT', 'phoneCode' => '370', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇱🇹'],
            ['countryName' => 'Luxembourg', 'iso3Code' => 'LUX', 'iso2Code' => 'LU', 'phoneCode' => '352', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇱🇺'],
            ['countryName' => 'Macau S.A.R.', 'iso3Code' => 'MAC', 'iso2Code' => 'MO', 'phoneCode' => '853', 'currencyCode' => 'MOP', 'currencyName' => 'Macanese pataca',    'currencySymbol' => '$', 'flagEmoji' => '🇲🇴'],
            ['countryName' => 'Macedonia', 'iso3Code' => 'MKD', 'iso2Code' => 'MK', 'phoneCode' => '389', 'currencyCode' => 'MKD', 'currencyName' => 'Denar',    'currencySymbol' => 'ден', 'flagEmoji' => '🇲🇰'],
            ['countryName' => 'Madagascar', 'iso3Code' => 'MDG', 'iso2Code' => 'MG', 'phoneCode' => '261', 'currencyCode' => 'MGA', 'currencyName' => 'Malagasy ariary',    'currencySymbol' => 'Ar', 'flagEmoji' => '🇲🇬'],
            ['countryName' => 'Malawi', 'iso3Code' => 'MWI', 'iso2Code' => 'MW', 'phoneCode' => '265', 'currencyCode' => 'MWK', 'currencyName' => 'Malawian kwacha',    'currencySymbol' => 'MK', 'flagEmoji' => '🇲🇼'],
            ['countryName' => 'Malaysia', 'iso3Code' => 'MYS', 'iso2Code' => 'MY', 'phoneCode' => '60', 'currencyCode' => 'MYR', 'currencyName' => 'Malaysian ringgit',    'currencySymbol' => 'RM', 'flagEmoji' => '🇲🇾'],
            ['countryName' => 'Maldives', 'iso3Code' => 'MDV', 'iso2Code' => 'MV', 'phoneCode' => '960', 'currencyCode' => 'MVR', 'currencyName' => 'Maldivian rufiyaa',    'currencySymbol' => 'Rf', 'flagEmoji' => '🇲🇻'],
            ['countryName' => 'Mali', 'iso3Code' => 'MLI', 'iso2Code' => 'ML', 'phoneCode' => '223', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇲🇱'],
            ['countryName' => 'Malta', 'iso3Code' => 'MLT', 'iso2Code' => 'MT', 'phoneCode' => '356', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇲🇹'],
            ['countryName' => 'Man (Isle of)', 'iso3Code' => 'IMN', 'iso2Code' => 'IM', 'phoneCode' => '+44-1624', 'currencyCode' => 'GBP', 'currencyName' => 'British pound',    'currencySymbol' => '£', 'flagEmoji' => '🇮🇲'],
            ['countryName' => 'Marshall Islands', 'iso3Code' => 'MHL', 'iso2Code' => 'MH', 'phoneCode' => '692', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇲🇭'],
            ['countryName' => 'Martinique', 'iso3Code' => 'MTQ', 'iso2Code' => 'MQ', 'phoneCode' => '596', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇲🇶'],
            ['countryName' => 'Mauritania', 'iso3Code' => 'MRT', 'iso2Code' => 'MR', 'phoneCode' => '222', 'currencyCode' => 'MRO', 'currencyName' => 'Mauritanian ouguiya',    'currencySymbol' => 'MRU', 'flagEmoji' => '🇲🇷'],
            ['countryName' => 'Mauritius', 'iso3Code' => 'MUS', 'iso2Code' => 'MU', 'phoneCode' => '230', 'currencyCode' => 'MUR', 'currencyName' => 'Mauritian rupee',    'currencySymbol' => '₨', 'flagEmoji' => '🇲🇺'],
            ['countryName' => 'Mayotte', 'iso3Code' => 'MYT', 'iso2Code' => 'YT', 'phoneCode' => '262', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇾🇹'],
            ['countryName' => 'Mexico', 'iso3Code' => 'MEX', 'iso2Code' => 'MX', 'phoneCode' => '52', 'currencyCode' => 'MXN', 'currencyName' => 'Mexican peso',    'currencySymbol' => '$', 'flagEmoji' => '🇲🇽'],
            ['countryName' => 'Micronesia', 'iso3Code' => 'FSM', 'iso2Code' => 'FM', 'phoneCode' => '691', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇫🇲'],
            ['countryName' => 'Moldova', 'iso3Code' => 'MDA', 'iso2Code' => 'MD', 'phoneCode' => '373', 'currencyCode' => 'MDL', 'currencyName' => 'Moldovan leu',    'currencySymbol' => 'L', 'flagEmoji' => '🇲🇩'],
            ['countryName' => 'Monaco', 'iso3Code' => 'MCO', 'iso2Code' => 'MC', 'phoneCode' => '377', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇲🇨'],
            ['countryName' => 'Mongolia', 'iso3Code' => 'MNG', 'iso2Code' => 'MN', 'phoneCode' => '976', 'currencyCode' => 'MNT', 'currencyName' => 'Mongolian tögrög',    'currencySymbol' => '₮', 'flagEmoji' => '🇲🇳'],
            ['countryName' => 'Montenegro', 'iso3Code' => 'MNE', 'iso2Code' => 'ME', 'phoneCode' => '382', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇲🇪'],
            ['countryName' => 'Montserrat', 'iso3Code' => 'MSR', 'iso2Code' => 'MS', 'phoneCode' => '+1-664', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇲🇸'],
            ['countryName' => 'Morocco', 'iso3Code' => 'MAR', 'iso2Code' => 'MA', 'phoneCode' => '212', 'currencyCode' => 'MAD', 'currencyName' => 'Moroccan dirham',    'currencySymbol' => 'DH', 'flagEmoji' => '🇲🇦'],
            ['countryName' => 'Mozambique', 'iso3Code' => 'MOZ', 'iso2Code' => 'MZ', 'phoneCode' => '258', 'currencyCode' => 'MZN', 'currencyName' => 'Mozambican metical',    'currencySymbol' => 'MT', 'flagEmoji' => '🇲🇿'],
            ['countryName' => 'Myanmar', 'iso3Code' => 'MMR', 'iso2Code' => 'MM', 'phoneCode' => '95', 'currencyCode' => 'MMK', 'currencyName' => 'Burmese kyat',    'currencySymbol' => 'K', 'flagEmoji' => '🇲🇲'],
            ['countryName' => 'Namibia', 'iso3Code' => 'NAM', 'iso2Code' => 'NA', 'phoneCode' => '264', 'currencyCode' => 'NAD', 'currencyName' => 'Namibian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇳🇦'],
            ['countryName' => 'Nauru', 'iso3Code' => 'NRU', 'iso2Code' => 'NR', 'phoneCode' => '674', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇳🇷'],
            ['countryName' => 'Nepal', 'iso3Code' => 'NPL', 'iso2Code' => 'NP', 'phoneCode' => '977', 'currencyCode' => 'NPR', 'currencyName' => 'Nepalese rupee',    'currencySymbol' => '₨', 'flagEmoji' => '🇳🇵'],
            ['countryName' => 'Bonaire, Sint Eustatius and Saba', 'iso3Code' => 'BES', 'iso2Code' => 'BQ', 'phoneCode' => '599', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇧🇶'],
            ['countryName' => 'Netherlands', 'iso3Code' => 'NLD', 'iso2Code' => 'NL', 'phoneCode' => '31', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇳🇱'],
            ['countryName' => 'New Caledonia', 'iso3Code' => 'NCL', 'iso2Code' => 'NC', 'phoneCode' => '687', 'currencyCode' => 'XPF', 'currencyName' => 'CFP franc',    'currencySymbol' => '₣', 'flagEmoji' => '🇳🇨'],
            ['countryName' => 'New Zealand', 'iso3Code' => 'NZL', 'iso2Code' => 'NZ', 'phoneCode' => '64', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇳🇿'],
            ['countryName' => 'Nicaragua', 'iso3Code' => 'NIC', 'iso2Code' => 'NI', 'phoneCode' => '505', 'currencyCode' => 'NIO', 'currencyName' => 'Nicaraguan córdoba',    'currencySymbol' => 'C$', 'flagEmoji' => '🇳🇮'],
            ['countryName' => 'Niger', 'iso3Code' => 'NER', 'iso2Code' => 'NE', 'phoneCode' => '227', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇳🇪'],
            ['countryName' => 'Nigeria', 'iso3Code' => 'NGA', 'iso2Code' => 'NG', 'phoneCode' => '234', 'currencyCode' => 'NGN', 'currencyName' => 'Nigerian naira',    'currencySymbol' => '₦', 'flagEmoji' => '🇳🇬'],
            ['countryName' => 'Niue', 'iso3Code' => 'NIU', 'iso2Code' => 'NU', 'phoneCode' => '683', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇳🇺'],
            ['countryName' => 'Norfolk Island', 'iso3Code' => 'NFK', 'iso2Code' => 'NF', 'phoneCode' => '672', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇳🇫'],
            ['countryName' => 'Northern Mariana Islands', 'iso3Code' => 'MNP', 'iso2Code' => 'MP', 'phoneCode' => '+1-670', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇲🇵'],
            ['countryName' => 'Norway', 'iso3Code' => 'NOR', 'iso2Code' => 'NO', 'phoneCode' => '47', 'currencyCode' => 'NOK', 'currencyName' => 'Norwegian krone',    'currencySymbol' => 'kr', 'flagEmoji' => '🇳🇴'],
            ['countryName' => 'Oman', 'iso3Code' => 'OMN', 'iso2Code' => 'OM', 'phoneCode' => '968', 'currencyCode' => 'OMR', 'currencyName' => 'Omani rial',    'currencySymbol' => '.ع.ر', 'flagEmoji' => '🇴🇲'],
            ['countryName' => 'Pakistan', 'iso3Code' => 'PAK', 'iso2Code' => 'PK', 'phoneCode' => '92', 'currencyCode' => 'PKR', 'currencyName' => 'Pakistani rupee',    'currencySymbol' => '₨', 'flagEmoji' => '🇵🇰'],
            ['countryName' => 'Palau', 'iso3Code' => 'PLW', 'iso2Code' => 'PW', 'phoneCode' => '680', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇵🇼'],
            ['countryName' => 'Palestinian Territory Occupied', 'iso3Code' => 'PSE', 'iso2Code' => 'PS', 'phoneCode' => '970', 'currencyCode' => 'ILS', 'currencyName' => 'Israeli new shekel',    'currencySymbol' => '₪', 'flagEmoji' => '🇵🇸'],
            ['countryName' => 'Panama', 'iso3Code' => 'PAN', 'iso2Code' => 'PA', 'phoneCode' => '507', 'currencyCode' => 'PAB', 'currencyName' => 'Panamanian balboa',    'currencySymbol' => 'B/.', 'flagEmoji' => '🇵🇦'],
            ['countryName' => 'Papua new Guinea', 'iso3Code' => 'PNG', 'iso2Code' => 'PG', 'phoneCode' => '675', 'currencyCode' => 'PGK', 'currencyName' => 'Papua New Guinean kina',    'currencySymbol' => 'K', 'flagEmoji' => '🇵🇬'],
            ['countryName' => 'Paraguay', 'iso3Code' => 'PRY', 'iso2Code' => 'PY', 'phoneCode' => '595', 'currencyCode' => 'PYG', 'currencyName' => 'Paraguayan guarani',    'currencySymbol' => '₲', 'flagEmoji' => '🇵🇾'],
            ['countryName' => 'Peru', 'iso3Code' => 'PER', 'iso2Code' => 'PE', 'phoneCode' => '51', 'currencyCode' => 'PEN', 'currencyName' => 'Peruvian sol',    'currencySymbol' => 'S/.', 'flagEmoji' => '🇵🇪'],
            ['countryName' => 'Philippines', 'iso3Code' => 'PHL', 'iso2Code' => 'PH', 'phoneCode' => '63', 'currencyCode' => 'PHP', 'currencyName' => 'Philippine peso',    'currencySymbol' => '₱', 'flagEmoji' => '🇵🇭'],
            ['countryName' => 'Pitcairn Island', 'iso3Code' => 'PCN', 'iso2Code' => 'PN', 'phoneCode' => '870', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇵🇳'],
            ['countryName' => 'Poland', 'iso3Code' => 'POL', 'iso2Code' => 'PL', 'phoneCode' => '48', 'currencyCode' => 'PLN', 'currencyName' => 'Polish złoty',    'currencySymbol' => 'zł', 'flagEmoji' => '🇵🇱'],
            ['countryName' => 'Portugal', 'iso3Code' => 'PRT', 'iso2Code' => 'PT', 'phoneCode' => '351', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇵🇹'],
            ['countryName' => 'Puerto Rico', 'iso3Code' => 'PRI', 'iso2Code' => 'PR', 'phoneCode' => '+1-787 and 1-939', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇵🇷'],
            ['countryName' => 'Qatar', 'iso3Code' => 'QAT', 'iso2Code' => 'QA', 'phoneCode' => '974', 'currencyCode' => 'QAR', 'currencyName' => 'Qatari riyal',    'currencySymbol' => 'ق.ر', 'flagEmoji' => '🇶🇦'],
            ['countryName' => 'Reunion', 'iso3Code' => 'REU', 'iso2Code' => 'RE', 'phoneCode' => '262', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇷🇪'],
            ['countryName' => 'Romania', 'iso3Code' => 'ROU', 'iso2Code' => 'RO', 'phoneCode' => '40', 'currencyCode' => 'RON', 'currencyName' => 'Romanian leu',    'currencySymbol' => 'lei', 'flagEmoji' => '🇷🇴'],
            ['countryName' => 'Russia', 'iso3Code' => 'RUS', 'iso2Code' => 'RU', 'phoneCode' => '7', 'currencyCode' => 'RUB', 'currencyName' => 'Russian ruble',    'currencySymbol' => '₽', 'flagEmoji' => '🇷🇺'],
            ['countryName' => 'Rwanda', 'iso3Code' => 'RWA', 'iso2Code' => 'RW', 'phoneCode' => '250', 'currencyCode' => 'RWF', 'currencyName' => 'Rwandan franc',    'currencySymbol' => 'FRw', 'flagEmoji' => '🇷🇼'],
            ['countryName' => 'Saint Helena', 'iso3Code' => 'SHN', 'iso2Code' => 'SH', 'phoneCode' => '290', 'currencyCode' => 'SHP', 'currencyName' => 'Saint Helena pound',    'currencySymbol' => '£', 'flagEmoji' => '🇸🇭'],
            ['countryName' => 'Saint Kitts And Nevis', 'iso3Code' => 'KNA', 'iso2Code' => 'KN', 'phoneCode' => '+1-869', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇰🇳'],
            ['countryName' => 'Saint Lucia', 'iso3Code' => 'LCA', 'iso2Code' => 'LC', 'phoneCode' => '+1-758', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇱🇨'],
            ['countryName' => 'Saint Pierre and Miquelon', 'iso3Code' => 'SPM', 'iso2Code' => 'PM', 'phoneCode' => '508', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇵🇲'],
            ['countryName' => 'Saint Vincent And The Grenadines', 'iso3Code' => 'VCT', 'iso2Code' => 'VC', 'phoneCode' => '+1-784', 'currencyCode' => 'XCD', 'currencyName' => 'Eastern Caribbean dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇻🇨'],
            ['countryName' => 'Saint-Barthelemy', 'iso3Code' => 'BLM', 'iso2Code' => 'BL', 'phoneCode' => '590', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇧🇱'],
            ['countryName' => 'Saint-Martin (French part)', 'iso3Code' => 'MAF', 'iso2Code' => 'MF', 'phoneCode' => '590', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇲🇫'],
            ['countryName' => 'Samoa', 'iso3Code' => 'WSM', 'iso2Code' => 'WS', 'phoneCode' => '685', 'currencyCode' => 'WST', 'currencyName' => 'Samoan tālā',    'currencySymbol' => 'SAT', 'flagEmoji' => '🇼🇸'],
            ['countryName' => 'San Marino', 'iso3Code' => 'SMR', 'iso2Code' => 'SM', 'phoneCode' => '378', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇸🇲'],
            ['countryName' => 'Sao Tome and Principe', 'iso3Code' => 'STP', 'iso2Code' => 'ST', 'phoneCode' => '239', 'currencyCode' => 'STD', 'currencyName' => 'Dobra',    'currencySymbol' => 'Db', 'flagEmoji' => '🇸🇹'],
            ['countryName' => 'Saudi Arabia', 'iso3Code' => 'SAU', 'iso2Code' => 'SA', 'phoneCode' => '966', 'currencyCode' => 'SAR', 'currencyName' => 'Saudi riyal',    'currencySymbol' => '﷼', 'flagEmoji' => '🇸🇦'],
            ['countryName' => 'Senegal', 'iso3Code' => 'SEN', 'iso2Code' => 'SN', 'phoneCode' => '221', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇸🇳'],
            ['countryName' => 'Serbia', 'iso3Code' => 'SRB', 'iso2Code' => 'RS', 'phoneCode' => '381', 'currencyCode' => 'RSD', 'currencyName' => 'Serbian dinar',    'currencySymbol' => 'din', 'flagEmoji' => '🇷🇸'],
            ['countryName' => 'Seychelles', 'iso3Code' => 'SYC', 'iso2Code' => 'SC', 'phoneCode' => '248', 'currencyCode' => 'SCR', 'currencyName' => 'Seychellois rupee',    'currencySymbol' => 'SRe', 'flagEmoji' => '🇸🇨'],
            ['countryName' => 'Sierra Leone', 'iso3Code' => 'SLE', 'iso2Code' => 'SL', 'phoneCode' => '232', 'currencyCode' => 'SLL', 'currencyName' => 'Sierra Leonean leone',    'currencySymbol' => 'Le', 'flagEmoji' => '🇸🇱'],
            ['countryName' => 'Singapore', 'iso3Code' => 'SGP', 'iso2Code' => 'SG', 'phoneCode' => '65', 'currencyCode' => 'SGD', 'currencyName' => 'Singapore dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇸🇬'],
            ['countryName' => 'Slovakia', 'iso3Code' => 'SVK', 'iso2Code' => 'SK', 'phoneCode' => '421', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇸🇰'],
            ['countryName' => 'Slovenia', 'iso3Code' => 'SVN', 'iso2Code' => 'SI', 'phoneCode' => '386', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇸🇮'],
            ['countryName' => 'Solomon Islands', 'iso3Code' => 'SLB', 'iso2Code' => 'SB', 'phoneCode' => '677', 'currencyCode' => 'SBD', 'currencyName' => 'Solomon Islands dollar',    'currencySymbol' => 'Si$', 'flagEmoji' => '🇸🇧'],
            ['countryName' => 'Somalia', 'iso3Code' => 'SOM', 'iso2Code' => 'SO', 'phoneCode' => '252', 'currencyCode' => 'SOS', 'currencyName' => 'Somali shilling',    'currencySymbol' => 'Sh.so.', 'flagEmoji' => '🇸🇴'],
            ['countryName' => 'South Africa', 'iso3Code' => 'ZAF', 'iso2Code' => 'ZA', 'phoneCode' => '27', 'currencyCode' => 'ZAR', 'currencyName' => 'South African rand',    'currencySymbol' => 'R', 'flagEmoji' => '🇿🇦'],
            ['countryName' => 'South Georgia', 'iso3Code' => 'SGS', 'iso2Code' => 'GS', 'phoneCode' => '500', 'currencyCode' => 'GBP', 'currencyName' => 'British pound',    'currencySymbol' => '£', 'flagEmoji' => '🇬🇸'],
            ['countryName' => 'South Sudan', 'iso3Code' => 'SSD', 'iso2Code' => 'SS', 'phoneCode' => '211', 'currencyCode' => 'SSP', 'currencyName' => 'South Sudanese pound',    'currencySymbol' => '£', 'flagEmoji' => '🇸🇸'],
            ['countryName' => 'Spain', 'iso3Code' => 'ESP', 'iso2Code' => 'ES', 'phoneCode' => '34', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇪🇸'],
            ['countryName' => 'Sri Lanka', 'iso3Code' => 'LKA', 'iso2Code' => 'LK', 'phoneCode' => '94', 'currencyCode' => 'LKR', 'currencyName' => 'Sri Lankan rupee',    'currencySymbol' => 'Rs', 'flagEmoji' => '🇱🇰'],
            ['countryName' => 'Sudan', 'iso3Code' => 'SDN', 'iso2Code' => 'SD', 'phoneCode' => '249', 'currencyCode' => 'SDG', 'currencyName' => 'Sudanese pound',    'currencySymbol' => '.س.ج', 'flagEmoji' => '🇸🇩'],
            ['countryName' => 'Suriname', 'iso3Code' => 'SUR', 'iso2Code' => 'SR', 'phoneCode' => '597', 'currencyCode' => 'SRD', 'currencyName' => 'Surinamese dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇸🇷'],
            ['countryName' => 'Svalbard And Jan Mayen Islands', 'iso3Code' => 'SJM', 'iso2Code' => 'SJ', 'phoneCode' => '47', 'currencyCode' => 'NOK', 'currencyName' => 'Norwegian Krone',    'currencySymbol' => 'kr', 'flagEmoji' => '🇸🇯'],
            ['countryName' => 'Swaziland', 'iso3Code' => 'SWZ', 'iso2Code' => 'SZ', 'phoneCode' => '268', 'currencyCode' => 'SZL', 'currencyName' => 'Lilangeni',    'currencySymbol' => 'E', 'flagEmoji' => '🇸🇿'],
            ['countryName' => 'Sweden', 'iso3Code' => 'SWE', 'iso2Code' => 'SE', 'phoneCode' => '46', 'currencyCode' => 'SEK', 'currencyName' => 'Swedish krona',    'currencySymbol' => 'kr', 'flagEmoji' => '🇸🇪'],
            ['countryName' => 'Switzerland', 'iso3Code' => 'CHE', 'iso2Code' => 'CH', 'phoneCode' => '41', 'currencyCode' => 'CHF', 'currencyName' => 'Swiss franc',    'currencySymbol' => 'CHf', 'flagEmoji' => '🇨🇭'],
            ['countryName' => 'Syria', 'iso3Code' => 'SYR', 'iso2Code' => 'SY', 'phoneCode' => '963', 'currencyCode' => 'SYP', 'currencyName' => 'Syrian pound',    'currencySymbol' => 'LS', 'flagEmoji' => '🇸🇾'],
            ['countryName' => 'Taiwan', 'iso3Code' => 'TWN', 'iso2Code' => 'TW', 'phoneCode' => '886', 'currencyCode' => 'TWD', 'currencyName' => 'New Taiwan dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇼'],
            ['countryName' => 'Tajikistan', 'iso3Code' => 'TJK', 'iso2Code' => 'TJ', 'phoneCode' => '992', 'currencyCode' => 'TJS', 'currencyName' => 'Tajikistani somoni',    'currencySymbol' => 'SM', 'flagEmoji' => '🇹🇯'],
            ['countryName' => 'Tanzania', 'iso3Code' => 'TZA', 'iso2Code' => 'TZ', 'phoneCode' => '255', 'currencyCode' => 'TZS', 'currencyName' => 'Tanzanian shilling',    'currencySymbol' => 'TSh', 'flagEmoji' => '🇹🇿'],
            ['countryName' => 'Thailand', 'iso3Code' => 'THA', 'iso2Code' => 'TH', 'phoneCode' => '66', 'currencyCode' => 'THB', 'currencyName' => 'Thai baht',    'currencySymbol' => '฿', 'flagEmoji' => '🇹🇭'],
            ['countryName' => 'Togo', 'iso3Code' => 'TGO', 'iso2Code' => 'TG', 'phoneCode' => '228', 'currencyCode' => 'XOF', 'currencyName' => 'West African CFA franc',    'currencySymbol' => 'CFA', 'flagEmoji' => '🇹🇬'],
            ['countryName' => 'Tokelau', 'iso3Code' => 'TKL', 'iso2Code' => 'TK', 'phoneCode' => '690', 'currencyCode' => 'NZD', 'currencyName' => 'New Zealand dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇰'],
            ['countryName' => 'Tonga', 'iso3Code' => 'TON', 'iso2Code' => 'TO', 'phoneCode' => '676', 'currencyCode' => 'TOP', 'currencyName' => 'Tongan paʻanga',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇴'],
            ['countryName' => 'Trinidad And Tobago', 'iso3Code' => 'TTO', 'iso2Code' => 'TT', 'phoneCode' => '+1-868', 'currencyCode' => 'TTD', 'currencyName' => 'Trinidad and Tobago dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇹'],
            ['countryName' => 'Tunisia', 'iso3Code' => 'TUN', 'iso2Code' => 'TN', 'phoneCode' => '216', 'currencyCode' => 'TND', 'currencyName' => 'Tunisian dinar',    'currencySymbol' => 'ت.د', 'flagEmoji' => '🇹🇳'],
            ['countryName' => 'Turkey', 'iso3Code' => 'TUR', 'iso2Code' => 'TR', 'phoneCode' => '90', 'currencyCode' => 'TRY', 'currencyName' => 'Turkish lira',    'currencySymbol' => '₺', 'flagEmoji' => '🇹🇷'],
            ['countryName' => 'Turkmenistan', 'iso3Code' => 'TKM', 'iso2Code' => 'TM', 'phoneCode' => '993', 'currencyCode' => 'TMT', 'currencyName' => 'Turkmenistan manat',    'currencySymbol' => 'T', 'flagEmoji' => '🇹🇲'],
            ['countryName' => 'Turks And Caicos Islands', 'iso3Code' => 'TCA', 'iso2Code' => 'TC', 'phoneCode' => '+1-649', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇨'],
            ['countryName' => 'Tuvalu', 'iso3Code' => 'TUV', 'iso2Code' => 'TV', 'phoneCode' => '688', 'currencyCode' => 'AUD', 'currencyName' => 'Australian dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇹🇻'],
            ['countryName' => 'Uganda', 'iso3Code' => 'UGA', 'iso2Code' => 'UG', 'phoneCode' => '256', 'currencyCode' => 'UGX', 'currencyName' => 'Ugandan shilling',    'currencySymbol' => 'USh', 'flagEmoji' => '🇺🇬'],
            ['countryName' => 'Ukraine', 'iso3Code' => 'UKR', 'iso2Code' => 'UA', 'phoneCode' => '380', 'currencyCode' => 'UAH', 'currencyName' => 'Ukrainian hryvnia',    'currencySymbol' => '₴', 'flagEmoji' => '🇺🇦'],
            ['countryName' => 'United Arab Emirates', 'iso3Code' => 'ARE', 'iso2Code' => 'AE', 'phoneCode' => '971', 'currencyCode' => 'AED', 'currencyName' => 'United Arab Emirates dirham',    'currencySymbol' => 'إ.د', 'flagEmoji' => '🇦🇪'],
            ['countryName' => 'United Kingdom', 'iso3Code' => 'GBR', 'iso2Code' => 'GB', 'phoneCode' => '44', 'currencyCode' => 'GBP', 'currencyName' => 'British pound',    'currencySymbol' => '£', 'flagEmoji' => '🇬🇧'],
            ['countryName' => 'United States', 'iso3Code' => 'USA', 'iso2Code' => 'US', 'phoneCode' => '1', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇺🇸'],
            ['countryName' => 'United States Minor Outlying Islands', 'iso3Code' => 'UMI', 'iso2Code' => 'UM', 'phoneCode' => '1', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇺🇲'],
            ['countryName' => 'Uruguay', 'iso3Code' => 'URY', 'iso2Code' => 'UY', 'phoneCode' => '598', 'currencyCode' => 'UYU', 'currencyName' => 'Uruguayan peso',    'currencySymbol' => '$', 'flagEmoji' => '🇺🇾'],
            ['countryName' => 'Uzbekistan', 'iso3Code' => 'UZB', 'iso2Code' => 'UZ', 'phoneCode' => '998', 'currencyCode' => 'UZS', 'currencyName' => 'Uzbekistani soʻm',    'currencySymbol' => 'лв', 'flagEmoji' => '🇺🇿'],
            ['countryName' => 'Vanuatu', 'iso3Code' => 'VUT', 'iso2Code' => 'VU', 'phoneCode' => '678', 'currencyCode' => 'VUV', 'currencyName' => 'Vanuatu vatu',    'currencySymbol' => 'VT', 'flagEmoji' => '🇻🇺'],
            ['countryName' => 'Vatican City State (Holy See)', 'iso3Code' => 'VAT', 'iso2Code' => 'VA', 'phoneCode' => '379', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇻🇦'],
            ['countryName' => 'Venezuela', 'iso3Code' => 'VEN', 'iso2Code' => 'VE', 'phoneCode' => '58', 'currencyCode' => 'VEF', 'currencyName' => 'Bolívar',    'currencySymbol' => 'Bs', 'flagEmoji' => '🇻🇪'],
            ['countryName' => 'Vietnam', 'iso3Code' => 'VNM', 'iso2Code' => 'VN', 'phoneCode' => '84', 'currencyCode' => 'VND', 'currencyName' => 'Vietnamese đồng',    'currencySymbol' => '₫', 'flagEmoji' => '🇻🇳'],
            ['countryName' => 'Virgin Islands (British)', 'iso3Code' => 'VGB', 'iso2Code' => 'VG', 'phoneCode' => '+1-284', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇻🇬'],
            ['countryName' => 'Virgin Islands (US)', 'iso3Code' => 'VIR', 'iso2Code' => 'VI', 'phoneCode' => '+1-340', 'currencyCode' => 'USD', 'currencyName' => 'United States dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇻🇮'],
            ['countryName' => 'Wallis And Futuna Islands', 'iso3Code' => 'WLF', 'iso2Code' => 'WF', 'phoneCode' => '681', 'currencyCode' => 'XPF', 'currencyName' => 'CFP franc',    'currencySymbol' => '₣', 'flagEmoji' => '🇼🇫'],
            ['countryName' => 'Western Sahara', 'iso3Code' => 'ESH', 'iso2Code' => 'EH', 'phoneCode' => '212', 'currencyCode' => 'MAD', 'currencyName' => 'Moroccan Dirham',    'currencySymbol' => 'MAD', 'flagEmoji' => '🇪🇭'],
            ['countryName' => 'Yemen', 'iso3Code' => 'YEM', 'iso2Code' => 'YE', 'phoneCode' => '967', 'currencyCode' => 'YER', 'currencyName' => 'Yemeni rial',    'currencySymbol' => '﷼', 'flagEmoji' => '🇾🇪'],
            ['countryName' => 'Zambia', 'iso3Code' => 'ZMB', 'iso2Code' => 'ZM', 'phoneCode' => '260', 'currencyCode' => 'ZMW', 'currencyName' => 'Zambian kwacha',    'currencySymbol' => 'ZK', 'flagEmoji' => '🇿🇲'],
            ['countryName' => 'Zimbabwe', 'iso3Code' => 'ZWE', 'iso2Code' => 'ZW', 'phoneCode' => '263', 'currencyCode' => 'ZWL', 'currencyName' => 'Zimbabwe Dollar',    'currencySymbol' => '$', 'flagEmoji' => '🇿🇼'],
            ['countryName' => 'Kosovo', 'iso3Code' => 'XKX', 'iso2Code' => 'XK', 'phoneCode' => '383', 'currencyCode' => 'EUR', 'currencyName' => 'Euro',    'currencySymbol' => '€', 'flagEmoji' => '🇽🇰'],
            ['countryName' => 'Curaçao', 'iso3Code' => 'CUW', 'iso2Code' => 'CW', 'phoneCode' => '599', 'currencyCode' => 'ANG', 'currencyName' => 'Netherlands Antillean guilder',    'currencySymbol' => 'ƒ', 'flagEmoji' => '🇨🇼'],
            ['countryName' => 'Sint Maarten (Dutch part)', 'iso3Code' => 'SXM', 'iso2Code' => 'SX', 'phoneCode' => '1721', 'currencyCode' => 'ANG', 'currencyName' => 'Netherlands Antillean guilder',    'currencySymbol' => 'ƒ', 'flagEmoji' => '🇸🇽'],

        ];

        foreach ($countryData as $country) {

            $location = $this->db->table('locationMaster')->where(['locationName' => $country['countryName'], 'locationType' => 'country'])->get()->getRow();

            if (is_null($location)) {
                $this->db->table('locationMaster')->insert(['locationName' => $country['countryName'], 'locationType' => 'country']);
                $locationId = $this->db->insertID();
            } else {
                $locationId = $location->locationId;
            }

            $countryRow = [
                "locationId" => $locationId,
                "countryName" => $country['countryName'],
                "phoneCode" => $country['phoneCode'],
                "iso3Code" => $country['iso3Code'],
                "iso2Code" => $country['iso2Code'],
                "currencyCode" => $country['currencyCode'],
                "currencyName" => $country['currencyName'],
                "currencySymbol" => $country['currencySymbol'],
                "flagEmoji" => $country['flagEmoji'],
            ];


            $this->db->table('countryMaster')->insert($countryRow);
        }

        // Record this seeder in seedHistory
        $this->db->table("seedHistory")->insert(['seedName' => $seedName, 'runAt' => date('Y-m-d H:i:s')]);
    }
}
