<?php

namespace Modules\Backend\System\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CreateQuoteMasterSeeder extends Seeder
{
    public function run()
    {
        // new logic added to maintain seed history for frequenct seed run
        $seedName = static::class;
        $exists = $this->db->table('seedHistory')->where('seedName', $seedName)->countAllResults();
        if ($exists > 0) {
            return;
        }

        $data = [
            [
                'quoteId' => 1,
                'tenantId' => 1,
                'quotes' => 'The secret of getting ahead is getting started.',
                'author' => 'Mark Twain',
                'group' => 'admin',
            ],
            [
                'quoteId' => 2,
                'tenantId' => 1,
                'quotes' => 'Growth is never by mere chance; it is the result of forces working together.',
                'author' => 'James Cash Penney',
                'group' => 'admin',
            ],
            [
                'quoteId' => 3,
                'tenantId' => 1,
                'quotes' => 'Success usually comes to those who are too busy to be looking for it.',
                'author' => 'Henry David Thoreau',
                'group' => 'admin',
            ],
            [
                'quoteId' => 4,
                'tenantId' => 1,
                'quotes' => 'The only limit to our realization of tomorrow is our doubts of today.',
                'author' => 'Franklin D. Roosevelt',
                'group' => 'admin',
            ],
            [
                'quoteId' => 5,
                'tenantId' => 1,
                'quotes' => 'Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort.',
                'author' => 'Paul J. Meyer',
                'group' => 'admin',
            ],
            [
                'quoteId' => 6,
                'tenantId' => 1,
                'quotes' => 'In the middle of difficulty lies opportunity.',
                'author' => 'Albert Einstein',
                'group' => 'admin',
            ],
            [
                'quoteId' => 7,
                'tenantId' => 1,
                'quotes' => 'Don’t watch the clock; do what it does. Keep going.',
                'author' => 'Sam Levenson',
                'group' => 'admin',
            ],
            [
                'quoteId' => 8,
                'tenantId' => 1,
                'quotes' => 'Your business is a reflection of you. It will only grow as much as you do.',
                'author' => '',
                'group' => 'admin',
            ],
            [
                'quoteId' => 9,
                'tenantId' => 1,
                'quotes' => 'The harder you work for something, the greater you\'ll feel when you achieve it.',
                'author' => '',
                'group' => 'admin',
            ],
            [
                'quoteId' => 10,
                'tenantId' => 1,
                'quotes' => 'Great things in business are never done by one person; they\'re done by a team of people.',
                'author' => 'Steve Jobs',
                'group' => 'admin',
            ],
            [
                'quoteId' => 11,
                'tenantId' => 1,
                'quotes' => 'The only way to do great work is to love what you do.',
                'author' => 'Steve Jobs',
                'group' => 'admin',
            ],
            [
                'quoteId' => 12,
                'tenantId' => 1,
                'quotes' => 'Sales are contingent upon the attitude of the salesman, not the attitude of the prospect.',
                'author' => 'W. Clement Stone',
                'group' => 'admin',
            ],
            [
                'quoteId' => 13,
                'tenantId' => 1,
                'quotes' => 'The key to success is to focus on goals, not obstacles.',
                'author' => '',
                'group' => 'admin',
            ],
            [
                'quoteId' => 14,
                'tenantId' => 1,
                'quotes' => 'Your most unhappy customers are your greatest source of learning.',
                'author' => 'Bill Gates',
                'group' => 'admin',
            ],
            [
                'quoteId' => 15,
                'tenantId' => 1,
                'quotes' => 'Opportunities don\'t happen, you create them.',
                'author' => 'Chris Grosser',
                'group' => 'admin',
            ],
            [
                'quoteId' => 16,
                'tenantId' => 1,
                'quotes' => 'Action is the foundational key to all success.',
                'author' => 'Pablo Picasso',
                'group' => 'admin',
            ],
            [
                'quoteId' => 17,
                'tenantId' => 1,
                'quotes' => 'The best way to predict the future is to create it.',
                'author' => 'Peter Drucker',
                'group' => 'admin',
            ],
            [
                'quoteId' => 18,
                'tenantId' => 1,
                'quotes' => 'Success is not just about making money. It’s about making a difference.',
                'author' => '',
                'group' => 'admin',
            ],
            [
                'quoteId' => 19,
                'tenantId' => 1,
                'quotes' => 'A goal without a plan is just a wish.',
                'author' => 'Antoine de Saint-Exupéry',
                'group' => 'admin',
            ],
            [
                'quoteId' => 20,
                'tenantId' => 1,
                'quotes' => 'You don’t build a business, you build people, and then people build the business.',
                'author' => 'Zig Ziglar',
                'group' => 'admin',
            ],
            [
                'quoteId' => 21,
                'tenantId' => 1,
                'quotes' => 'Small daily improvements are the key to staggering long-term results.',
                'author' => '',
                'group' => 'admin',
            ],
            [
                'quoteId' => 22,
                'tenantId' => 1,
                'quotes' => 'Success is walking from failure to failure with no loss of enthusiasm.',
                'author' => 'Winston Churchill',
                'group' => 'admin',
            ],
            [
                'quoteId' => 23,
                'tenantId' => 1,
                'quotes' => 'The only place where success comes before work is in the dictionary.',
                'author' => 'Vidal Sassoon',
                'group' => 'admin',
            ],
            [
                'quoteId' => 24,
                'tenantId' => 1,
                'quotes' => 'Do not be embarrassed by your failures, learn from them and start again.',
                'author' => 'Richard Branson',
                'group' => 'admin',
            ],
            [
                'quoteId' => 25,
                'tenantId' => 1,
                'quotes' => 'Success is the sum of small efforts, repeated day in and day out.',
                'author' => 'Robert Collier',
                'group' => 'admin',
            ],
            [
                'quoteId' => 26,
                'tenantId' => 1,
                'quotes' => 'The future belongs to those who believe in the beauty of their dreams.',
                'author' => 'Eleanor Roosevelt',
                'group' => 'admin',
            ],
            [
                'quoteId' => 27,
                'tenantId' => 1,
                'quotes' => 'If you really want to do something, you\'ll find a way. If you don\'t, you\'ll find an excuse.',
                'author' => 'Jim Rohn',
                'group' => 'admin',
            ],
            [
                'quoteId' => 28,
                'tenantId' => 1,
                'quotes' => 'Quality is more important than quantity. One home run is much better than two doubles.',
                'author' => 'Steve Jobs',
                'group' => 'admin',
            ],
            [
                'quoteId' => 29,
                'tenantId' => 1,
                'quotes' => 'Success is not final; failure is not fatal: It is the courage to continue that counts.',
                'author' => 'Winston Churchill',
                'group' => 'admin',
            ],
            [
                'quoteId' => 30,
                'tenantId' => 1,
                'quotes' => 'Your time is limited, so don’t waste it living someone else’s life.',
                'author' => 'Steve Jobs',
                'group' => 'admin',
            ],
            [
                'quoteId' => 31,
                'tenantId' => 1,
                'quotes' => 'Business opportunities are like buses, there’s always another one coming.',
                'author' => 'Richard Branson',
                'group' => 'admin',
            ],
            [
                'quoteId' => 32,
                'tenantId' => 1,
                'quotes' => 'Don’t let yesterday take up too much of today.',
                'author' => 'Will Rogers',
                'group' => 'admin',
            ],
            [
                'quoteId' => 33,
                'tenantId' => 1,
                'quotes' => 'The difference between ordinary and extraordinary is that little extra.',
                'author' => 'Jimmy Johnson',
                'group' => 'admin',
            ],
            [
                'quoteId' => 34,
                'tenantId' => 1,
                'quotes' => 'The way to get started is to quit talking and begin doing.',
                'author' => 'Walt Disney',
                'group' => 'admin',
            ],
            [
                'quoteId' => 35,
                'tenantId' => 1,
                'quotes' => 'The best revenge is massive success.',
                'author' => 'Frank Sinatra',
                'group' => 'admin',
            ],
            [
                'quoteId' => 36,
                'tenantId' => 1,
                'quotes' => 'Success doesn’t come from what you do occasionally, it comes from what you do consistently.',
                'author' => 'Marie Forleo',
                'group' => 'admin',
            ],
            [
                'quoteId' => 37,
                'tenantId' => 1,
                'quotes' => 'Challenges are what make life interesting and overcoming them is what makes life meaningful.',
                'author' => 'Joshua J. Marine',
                'group' => 'admin',
            ],
            [
                'quoteId' => 38,
                'tenantId' => 1,
                'quotes' => 'Don’t be afraid to give up the good to go for the great.',
                'author' => 'John D. Rockefeller',
                'group' => 'admin',
            ],
            [
                'quoteId' => 39,
                'tenantId' => 1,
                'quotes' => 'It’s not about ideas. It’s about making ideas happen.',
                'author' => 'Scott Belsky',
                'group' => 'admin',
            ],
            [
                'quoteId' => 40,
                'tenantId' => 1,
                'quotes' => 'The function of leadership is to produce more leaders, not more followers.',
                'author' => 'Ralph Nader',
                'group' => 'admin',
            ],
            [
                'quoteId' => 41,
                'tenantId' => 1,
                'quotes' => 'Success in management requires learning as fast as the world is changing.',
                'author' => 'Warren Bennis',
                'group' => 'admin',
            ],
            [
                'quoteId' => 42,
                'tenantId' => 1,
                'quotes' => 'The harder you work for something, the greater you’ll feel when you achieve it.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 43,
                'tenantId' => 1,
                'quotes' => 'Success is not just about making money, it’s about making a difference.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 44,
                'tenantId' => 1,
                'quotes' => 'Loyalty is the foundation of teamwork. Without trust, there is no team.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 45,
                'tenantId' => 1,
                'quotes' => 'Your work is a reflection of your character. Strive for excellence every day.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 46,
                'tenantId' => 1,
                'quotes' => 'Sales are about building relationships, not just transactions.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 47,
                'tenantId' => 1,
                'quotes' => 'Punctuality is not just about being on time; it\'s about respecting others\' time and valuing your commitments.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 48,
                'tenantId' => 1,
                'quotes' => 'Honesty and integrity are the cornerstones of success in both business and life.',
                'author' => 'Mary Kay Ash',
                'group' => 'staff',
            ],
            [
                'quoteId' => 49,
                'tenantId' => 1,
                'quotes' => 'Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust. Overcome them with dedication.',
                'author' => 'Zig Ziglar',
                'group' => 'staff',
            ],
            [
                'quoteId' => 50,
                'tenantId' => 1,
                'quotes' => 'The only way to achieve the impossible is to believe it is possible.',
                'author' => 'Charles Kingsleigh',
                'group' => 'staff',
            ],
            [
                'quoteId' => 51,
                'tenantId' => 1,
                'quotes' => 'Productivity is never an accident. It’s the result of a commitment to excellence, intelligent planning, and focused effort.',
                'author' => 'Paul J. Meyer',
                'group' => 'staff',
            ],
            [
                'quoteId' => 52,
                'tenantId' => 1,
                'quotes' => 'Success is the result of preparation, hard work, and learning from failure.',
                'author' => 'Colin Powell',
                'group' => 'staff',
            ],
            [
                'quoteId' => 53,
                'tenantId' => 1,
                'quotes' => 'Sales are not about pushing products, but about solving problems.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 54,
                'tenantId' => 1,
                'quotes' => 'Dedication is doing what needs to be done, even when you don’t want to do it.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 55,
                'tenantId' => 1,
                'quotes' => 'Trust is the glue of life. It’s the most essential ingredient in effective communication.',
                'author' => 'Stephen Covey',
                'group' => 'staff',
            ],
            [
                'quoteId' => 56,
                'tenantId' => 1,
                'quotes' => 'Your energy introduces you before you even speak. Bring positivity and enthusiasm to every interaction.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 57,
                'tenantId' => 1,
                'quotes' => 'The way to get ahead is to start now, and to keep your promises.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 58,
                'tenantId' => 1,
                'quotes' => 'Integrity is choosing your thoughts and actions based on values rather than personal gain.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 59,
                'tenantId' => 1,
                'quotes' => 'Every job is a self-portrait of the person who did it. Autograph your work with excellence.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 60,
                'tenantId' => 1,
                'quotes' => 'Your attitude, not your aptitude, will determine your altitude.',
                'author' => 'Zig Ziglar',
                'group' => 'staff',
            ],
            [
                'quoteId' => 61,
                'tenantId' => 1,
                'quotes' => 'Success is the sum of small efforts, repeated day in and day out.',
                'author' => 'Robert Collier',
                'group' => 'staff',
            ],
            [
                'quoteId' => 62,
                'tenantId' => 1,
                'quotes' => 'Loyal employees create loyal customers.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 63,
                'tenantId' => 1,
                'quotes' => 'Don’t count the days, make the days count.',
                'author' => 'Muhammad Ali',
                'group' => 'staff',
            ],
            [
                'quoteId' => 64,
                'tenantId' => 1,
                'quotes' => 'Ethics is knowing the difference between what you have a right to do and what is right to do.',
                'author' => 'Potter Stewart',
                'group' => 'staff',
            ],
            [
                'quoteId' => 65,
                'tenantId' => 1,
                'quotes' => 'Every accomplishment starts with the decision to try.',
                'author' => 'John F. Kennedy',
                'group' => 'staff',
            ],
            [
                'quoteId' => 66,
                'tenantId' => 1,
                'quotes' => 'Success is walking from failure to failure with no loss of enthusiasm.',
                'author' => 'Winston Churchill',
                'group' => 'staff',
            ],
            [
                'quoteId' => 67,
                'tenantId' => 1,
                'quotes' => 'Being productive isn’t just about getting more done, it’s about making sure you’re working on the right things.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 68,
                'tenantId' => 1,
                'quotes' => 'Honesty is the fastest way to prevent a mistake from turning into a failure.',
                'author' => 'James Altucher',
                'group' => 'staff',
            ],
            [
                'quoteId' => 69,
                'tenantId' => 1,
                'quotes' => 'Be the kind of employee that others look up to, and the kind of person you’d want to work with.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 70,
                'tenantId' => 1,
                'quotes' => 'Do what you do so well that they will want to see it again and bring their friends.',
                'author' => 'Walt Disney',
                'group' => 'staff',
            ],
            [
                'quoteId' => 71,
                'tenantId' => 1,
                'quotes' => 'The only way to do great work is to love what you do.',
                'author' => 'Steve Jobs',
                'group' => 'staff',
            ],
            [
                'quoteId' => 72,
                'tenantId' => 1,
                'quotes' => 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.',
                'author' => 'Albert Schweitzer',
                'group' => 'staff',
            ],
            [
                'quoteId' => 73,
                'tenantId' => 1,
                'quotes' => 'Good things come to those who hustle.',
                'author' => 'Anais Nin',
                'group' => 'staff',
            ],
            [
                'quoteId' => 74,
                'tenantId' => 1,
                'quotes' => 'Loyalty means giving me your honest opinion, whether you think I\'ll like it or not.',
                'author' => 'General Colin Powell',
                'group' => 'staff',
            ],
            [
                'quoteId' => 75,
                'tenantId' => 1,
                'quotes' => 'Don’t aim for success if you want it; just do what you love and believe in, and it will come naturally.',
                'author' => 'David Frost',
                'group' => 'staff',
            ],
            [
                'quoteId' => 76,
                'tenantId' => 1,
                'quotes' => 'Efficiency is doing things right; effectiveness is doing the right things.',
                'author' => 'Peter Drucker',
                'group' => 'staff',
            ],
            [
                'quoteId' => 77,
                'tenantId' => 1,
                'quotes' => 'Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 78,
                'tenantId' => 1,
                'quotes' => 'A satisfied customer is the best business strategy of all.',
                'author' => 'Michael LeBoeuf',
                'group' => 'staff',
            ],
            [
                'quoteId' => 79,
                'tenantId' => 1,
                'quotes' => 'The greatest ability is dependability.',
                'author' => 'Bob Jones Sr.',
                'group' => 'staff',
            ],
            [
                'quoteId' => 80,
                'tenantId' => 1,
                'quotes' => 'The extra mile is a vast, unpopulated wasteland. But it’s where you find greatness.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 81,
                'tenantId' => 1,
                'quotes' => 'Your work ethic should be your signature, not your words.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 82,
                'tenantId' => 1,
                'quotes' => 'Success is not how high you have climbed, but how you make a positive difference to the world.',
                'author' => 'Roy T. Bennett',
                'group' => 'staff',
            ],
            [
                'quoteId' => 83,
                'tenantId' => 1,
                'quotes' => 'Loyalty is not a word, it’s a lifestyle.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 84,
                'tenantId' => 1,
                'quotes' => 'The best way to predict your future is to create it.',
                'author' => 'Peter Drucker',
                'group' => 'staff',
            ],
            [
                'quoteId' => 85,
                'tenantId' => 1,
                'quotes' => 'Effort only fully releases its reward after a person refuses to quit.',
                'author' => 'Napoleon Hill',
                'group' => 'staff',
            ],
            [
                'quoteId' => 86,
                'tenantId' => 1,
                'quotes' => 'Sales don’t happen by chance; they happen by choice.',
                'author' => '',
                'group' => 'staff',
            ],
            [
                'quoteId' => 87,
                'tenantId' => 1,
                'quotes' => 'Success is liking yourself, liking what you do, and liking how you do it.',
                'author' => 'Maya Angelou',
                'group' => 'staff',
            ],
            [
                'quoteId' => 88,
                'tenantId' => 1,
                'quotes' => 'Discipline is the bridge between goals and accomplishment.',
                'author' => 'Jim Rohn',
                'group' => 'staff',
            ],
            [
                'quoteId' => 89,
                'tenantId' => 1,
                'quotes' => 'The only thing standing between you and outrageous success is continuous progress.',
                'author' => 'Dan Waldschmidt',
                'group' => 'staff',
            ],
            [
                'quoteId' => 90,
                'tenantId' => 1,
                'quotes' => 'A good reputation is more valuable than money.',
                'author' => 'Publilius Syrus',
                'group' => 'staff',
            ],
        ];

        $this->db->table('quoteMaster')->insertBatch($data);

        // Record this seeder in seedHistory
        $this->db->table("seedHistory")->insert(['seedName' => $seedName, 'runAt' => date('Y-m-d H:i:s')]);
    }
}
