<?php

namespace Modules\Backend\System\Database\Seeds;

use CodeIgniter\Database\Seeder;

class StatusMasterData extends Seeder
{
    public $priority = 5;

    public function run()
    {
        $seedName = static::class;
        $exists = $this->db->table('seedHistory')->where('seedName', $seedName)->countAllResults();
        if ($exists > 0) {
            return;
        }

        $data = [
            [
                "tenantId" => 1,
                "statusName" => "Fresh Lead",
                ////"module" => "Lead",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-fire-flame-simple",
                "textColor" => "#7445ee",
                "bgColor" => "#d9d2e9",
                "sequence" => "1",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "In Followup",
                ////"module" => "Lead",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-phone",
                "textColor" => "#cc4400",
                "bgColor" => "#ffeee6",
                "sequence" => "2",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Deal Done",
                ////"module" => "Lead",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-thumbs-up",
                "textColor" => "#009933",
                "bgColor" => "#e6ffee",
                "sequence" => "3",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Cancelled",
                ////"module" => "Lead",
                "statusType" => "Lost",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 1,
                "icon" => "fa fa-close",
                "textColor" => "#e60000",
                "bgColor" => "#ffe6e6",
                "sequence" => "4",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Not Interested",
                ////"module" => "Lead",
                "statusType" => "Lost",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-ban",
                "textColor" => "#996633",
                "bgColor" => "#ffffe6",
                "sequence" => "5",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Not In Product",
                ////"module" => "Lead",
                "statusType" => "Lost",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-product-hunt",
                "textColor" => "#000000",
                "bgColor" => "#e0e0eb",
                "sequence" => "6",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "In Review",
                ////"module" => "Lead",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-star",
                "textColor" => "#660066",
                "bgColor" => "#ffe6ff",
                "sequence" => "7",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Order Received",
                //"module" => "Order",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-leaf",
                "textColor" => "#c36909",
                "bgColor" => "#fef3e7",
                "sequence" => "8",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "In Progress",
                //"module" => "Order",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-diagram-project",
                "textColor" => "#008000",
                "bgColor" => "#e6ffe6",
                "sequence" => "9",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],

            [
                "tenantId" => 1,
                "statusName" => "Completed",
                //"module" => "Order",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-check-double",
                "textColor" => "#006666",
                "bgColor" => "#e6ffff",
                "sequence" => "10",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],

            [
                "tenantId" => 1,
                "statusName" => "Cancelled",
                //"module" => "Order",
                "statusType" => "Lost",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-ban",
                "textColor" => "#862d59",
                "bgColor" => "#f9ecf2",
                "sequence" => "11",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Pending",
                //"module" => "orderPayment",
                "statusType" => "Open",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-info-circle",
                "textColor" => "#000099",
                "bgColor" => "#e6eeff",
                "sequence" => "12",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Approved",
                //"module" => "orderPayment",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fa fa-thumbs-up",
                "textColor" => "#009933",
                "bgColor" => "#e6ffee",
                "sequence" => "13",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Reject",
                //"module" => "orderPayment",
                "statusType" => "Lost",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-ban",
                "textColor" => "#862d59",
                "bgColor" => "#f9ecf2",
                "sequence" => "14",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Dispatched",
                //"module" => "DispatchMaster",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-file-invoice",
                "textColor" => "#8A2BE2",
                "bgColor" => "#FFEBCD",
                "sequence" => "15",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Invoice Generated",
                //"module" => "DispatchMaster",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-file-invoice",
                "textColor" => "#BC8F8F ",
                "bgColor" => "#F0E68C",
                "sequence" => "16",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],
            [
                "tenantId" => 1,
                "statusName" => "Invoice Generated",
                //"module" => "Sales Invoice",
                "statusType" => "Won",
                "isDefaultEntry" => 1,
                "isEditable" => 0,
                "isAction" => 0,
                "icon" => "fas fa-file-invoice",
                "textColor" => "#006666",
                "bgColor" => "#e6ffff",
                "sequence" => "17",
                "isActive" => 1,
                "isDeleted" => 0,
                "updatedAt" => date("Y-m-d H:i:s"),
                "updatedBy" => 1,
                "createdAt" => date("Y-m-d H:i:s"),
                "createdBy" => 1
            ],

        ];


        $this->db->table('statusMaster')->insertBatch($data);

        // Record this seeder in seedHistory
        $this->db->table("seedHistory")->insert(['seedName' => $seedName, 'runAt' => date('Y-m-d H:i:s')]);
    }
}
